name: ElementSmpUtility
version: '1.0-SNAPSHOT'
main: hs.elementSmpUtility.ElementSmpUtility
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]

commands:
  customblock:
    description: Manage custom blocks
    usage: /customblock <give|list> [args]
    aliases: [cb, cblock]
    permission: elementsmp.customblock

permissions:
  elementsmp.customblock:
    description: Allows use of custom block commands
    default: op