name: ElementSmpUtility
version: '1.0-SNAPSHOT'
main: hs.elementSmpUtility.ElementSmpUtility
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]

commands:
  customblock:
    description: Manage custom blocks
    usage: /customblock <give|list> [args]
    aliases: [cb, cblock]
    permission: elementsmp.customblock

  structure:
    description: Generate structures from NBT files
    usage: /structure <generate|list|reload> [args]
    aliases: [struct, gen]
    permission: elementsmp.structure

permissions:
  elementsmp.customblock:
    description: Allows use of custom block commands
    default: op

  elementsmp.structure:
    description: Allows use of structure generation commands
    default: op