name: ElementSmpUtility
version: '1.0-SNAPSHOT'
main: hs.elementSmpUtility.ElementSmpUtility
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]

commands:
  customblock:
    description: Manage custom blocks
    usage: /customblock <give|list> [args]
    aliases: [cb, cblock]
    permission: elementsmp.customblock

  temple:
    description: Manage temple structures
    usage: /temple <spawn|info> [args]
    aliases: [t, templ]
    permission: elementsmp.temple

  custommodels:
    description: Main CustomModels command
    usage: /custommodels <give|list|info|reload|generate>
    aliases: [ cm, cmodels, custommodel ]
    permission: custommodels.use

permissions:
  elementsmp.customblock:
    description: Allows use of custom block commands
    default: op

  elementsmp.temple:
    description: Allows spawning and managing temples
    default: op

  elementsmp.*:
    description: Grants all ElementSMP permissions
    default: op
    children:
      elementsmp.customblock: true
      elementsmp.temple: true

  custommodels.*:
    description: Grants all CustomModels permissions
    default: op
    children:
      custommodels.use: true
      custommodels.give: true
      custommodels.list: true
      custommodels.info: true
      custommodels.reload: true
      custommodels.generate: true

    custommodels.use:
      description: Allows basic usage of CustomModels commands
      default: true

    custommodels.give:
      description: Allows giving custom model items
      default: op

    custommodels.list:
      description: Allows listing all custom models
      default: true

    custommodels.info:
      description: Allows viewing model information
      default: true

    custommodels.reload:
      description: Allows reloading plugin configuration
      default: op

    custommodels.generate:
      description: Allows generating resource packs
      default: op