name: ElementSmpUtility
version: '1.0-SNAPSHOT'
main: hs.elementSmpUtility.ElementSmpUtility
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]

commands:
  customblock:
    description: Manage custom blocks
    usage: /customblock <give|list> [args]
    aliases: [cb, cblock]
    permission: elementsmp.customblock

  temple:
    description: Manage temple structures
    usage: /temple <spawn|info> [args]
    aliases: [t, templ]
    permission: elementsmp.temple

permissions:
  elementsmp.customblock:
    description: Allows use of custom block commands
    default: op

  elementsmp.temple:
    description: Allows spawning and managing temples
    default: op

  elementsmp.*:
    description: Grants all ElementSMP permissions
    default: op
    children:
      elementsmp.customblock: true
      elementsmp.temple: true