name: ElementSmpUtility
version: '1.0-SNAPSHOT'
main: hs.elementSmpUtility.ElementSmpUtility
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]

commands:
  customblock:
    description: Manage custom blocks
    usage: /customblock <give|list> [args]
    aliases: [cb, cblock]
    permission: elementsmp.customblock

  pedestal:
    description: Manage pedestal storage
    usage: /pedestal <info|reload>
    permission: elementsmp.pedestal.admin

permissions:
  elementsmp.customblock:
    description: Allows use of custom block commands
    default: op

  elementsmp.pedestal.admin:
    description: Allows use of pedestal admin commands
    default: op